import random

def overall_mood(energy):
    energyMessages = {
    1: [
        "Your overall mood today feels completely drained.",
        "You reported feeling very low on energy today.",
        "You're running on empty right now — it's okay to rest.",
        "Today feels like a total recharge day — take it slow.",
        "Energy is at rock bottom — a recovery moment might help."
        "You’re completely drained today.",
        "Your tank is totally empty — take it easy.",
        "Energy is rock bottom right now.",
        "This is a full rest-and-recover day.",
        "Your feels heavy and exhausting.",
        "Energy is at zero — perfect time to slow down.",
        "Your system needs serious rest today.",
        "Even small tasks may feel overwhelming right now.",
        "Today feels like a full stop — and that’s okay.",
        "You're in deep low-power mode right now.",
        "Energy bottomed out — no need to push today.",
        "Everything might feel like climbing a mountain today.",
        "You're in full recovery territory right now.",
        "This is one of those complete shutdown days — be kind to yourself.",
         "You feel completely drained — today’s about rest, not results.",
        "Your energy is empty right now. Give yourself full permission to slow down.",
        "Everything feels heavy today — focus only on breathing and existing gently.",
        "You’re fully depleted — no pressure, just rest and recover.",
        "Today’s not for productivity; it’s for healing and stillness.",
        "Your mind and body need deep rest — be gentle with yourself.",
        "You’re on empty right now — recovery is the only task today.",
        "Energy’s gone quiet — let yourself pause without guilt.",
        "Today feels like a shutdown moment — that’s your body asking for care.",
        "You’re at zero — recharge mode isn’t laziness, it’s maintenance.",
        "Even small actions may feel impossible — take that as a signal to stop.",
        "You’ve hit your limit — rest isn’t optional, it’s needed.",
        "You’re carrying too much fatigue — unplug fully if you can.",
        "Everything feels slow and dense — today’s goal: stillness.",
        "You’re out of fuel — rest is the most productive thing you can do.",
        "Your body’s saying enough — listen before burnout deepens.",
        "Energy bottomed out — be radically kind to yourself today.",
        "Today’s not a performance day — it’s a healing one.",
        "You’re deep in recovery territory — stop pushing, start resting.",
        "Even thinking feels heavy — silence is your medicine today."
    ],
    2: [
        "Your energy’s fading — take it slow and treat yourself softly today.",
        "You’re running low — choose comfort over effort right now.",
        "Today feels heavy — it’s okay to let things wait.",
        "You’re on the edge of exhaustion — recharge before you break down.",
        "Your body’s whispering: rest before it starts shouting.",
        "You’re low on energy, but showing up still counts.",
        "This is a fragile day — protect your peace and space.",
        "You’re close to empty — light tasks, warm meals, slow pace.",
        "Even small things feel like effort — simplify and breathe.",
        "You’re running near burnout — pause before pushing.",
        "Your energy is fragile — let gentleness be your rhythm.",
        "This is a low-power day — rest isn’t quitting, it’s recharging.",
        "You might feel foggy — move only if it restores you.",
        "Everything feels like walking through mud — slow and steady.",
        "Your system’s tired — refill your energy in quiet ways.",
        "Low energy doesn’t mean failure — it means you’ve been trying hard.",
        "You’re running low — even sitting still is progress today.",
        "This is a near-empty day — give yourself permission to stop.",
        "Your energy’s dim — soft light, slow music, no pressure.",
        "Rest deeply. Today’s not for output — it’s for recovery."
    ],
    3: [
        "Your energy is low today.",
        "You may feel tired or sluggish.",
        "This is a slow-moving kind of day.",
        "You’re not at your best, but you’re here.",
        "Energy feels dull — small steps count.",
        "You're dragging a bit, but still showing up.",
        "This is a low-focus, low-drive day.",
        "Even simple tasks may feel draining.",
        "You're taking it slow today.",
        "This is a below-average energy day.",
        "Energy feels flat — not terrible, not great.",
        "You might need an extra push to get moving.",
        "Motivation may be hard to find right now.",
        "This is a good day for light activities only.",
        "You're a bit undercharged today.",
        "Energy is dipping but not gone entirely.",
        "Your body is signaling a need to slow down.",
        "Today calls for gentle effort.",
        "You might be feeling sluggish or foggy.",
        "Energy is low but still present — a light boost may help.",
        "You seem to have low energy today.",
        "Energy feels sluggish — maybe a good time to recharge.",
        "Today's check-in points to a slower-paced mood.",
        "You might be feeling a bit run down right now.",
        "Energy is dipping — a short walk or rest could help reset.",
         "You’re a bit drained — slow down and be gentle with yourself.",
        "Energy’s dipping — don’t rush, today’s about doing less.",
        "You’re low but steady — small movements, not big leaps.",
        "Fatigue’s creeping in — give yourself grace today.",
        "Your tank’s low — focus on what truly matters only.",
        "You’re running slower than usual — that’s completely fine.",
        "This is a sluggish day — just existing is enough.",
        "You’re tired but still here — that’s resilience.",
        "Energy feels thin — stretch your rest, not your effort.",
        "You’re moving through molasses — go easy.",
        "Low energy doesn’t erase progress — it refines your limits.",
        "You’re not empty, just slower — that’s still movement.",
        "Today’s about pacing, not productivity.",
        "You’re in low gear — keep it simple.",
        "Energy’s muted — respond, don’t react.",
        "You’re not lazy; you’re rebalancing.",
        "Tired doesn’t mean weak — it means human.",
        "You’re functioning on low power — be proud of showing up.",
        "Fatigue’s temporary — go easy until it passes.",
        "You’re not broken — you’re recharging, quietly."
        ],
    4: [
          "You’re a little off today — ease through the motions gently.",
        "Energy’s a bit dim — focus on calm over control.",
        "You’re slightly tired — no need to overcompensate.",
        "This is a low-effort day — flow softly.",
        "You’re steady, just slower — that’s okay.",
        "Your energy’s quiet, not gone — nurture it.",
        "You feel a bit muted — low-key is fine today.",
        "Slight fatigue’s hanging around — rest when needed.",
        "You’re a step below your norm — honor that.",
        "This is a soft-energy day — quiet productivity works best.",
        "Energy’s reserved — conserve it wisely.",
        "You’re slower, but still steady — consistency matters more than speed.",
        "This is an introspective mood — stay gentle with thoughts.",
        "You’re not fully charged, but still capable.",
        "Low pressure days like this prevent burnout.",
        "You’re calm, but not driven — that’s valid.",
        "Today’s about balance, not output.",
        "Energy’s low, but your awareness is high.",
        "Move at half-speed — it’s still progress.",
        "You’re slightly under, but grounded."
        ],
    5: [
        "Your overall mood today feels neutral.",
         "You’re steady today — balanced and present.",
        "Energy’s even — a calm, neutral day.",
        "You’re centered — neither drained nor charged.",
        "This is a stable day — quiet but grounded.",
        "You’re balanced — everything’s in moderation today.",
        "Energy’s level — a baseline worth appreciating.",
        "You’re in neutral gear — steady forward motion.",
        "Calm energy defines your day — smooth sailing.",
        "You’re balanced between effort and ease.",
        "Energy’s calm — focus feels natural today.",
        "Nothing extreme — just steady and consistent.",
        "You’re emotionally centered — great ground for reflection.",
        "This is a peaceful midpoint day.",
        "You’re even-tempered and in rhythm.",
        "Energy’s quiet but reliable.",
        "You’re maintaining a healthy middle ground.",
        "You’re balanced — that’s a quiet win.",
        "This is a maintenance mode kind of day.",
        "Energy’s harmonious — good place to build from.",
        "You’re steady, grounded, and stable today."
        ],
    6: [
        "Your energy is slightly above neutral today.",
        "You’re gently uplifted — calm motivation is flowing.",
        "Energy’s light and open — ideal for easy progress.",
        "You feel slightly elevated — positivity with balance.",
        "This is a mild uptrend day — quiet confidence growing.",
        "Energy feels smooth and cooperative today.",
        "You’re leaning toward optimism — enjoy it.",
        "You’re subtly energized — it’s a good flow.",
        "Calm focus defines your day — strong but steady.",
        "You’re in a good rhythm — not rushed, just aligned.",
        "Energy’s steady with a warm lift.",
        "You feel easygoing and ready.",
        "This is a content, grounded high.",
        "Energy’s pleasant and stable — a great mindset zone.",
        "You’re balanced but brighter than usual.",
        "This is quiet motivation — consistent, calm effort.",
        "You’re aligned and flowing forward.",
        "Energy’s light — it supports you naturally.",
        "You’re entering a small peak — stable positivity.",
        "This is a gentle, feel-good day.",
        "Energy’s warm and supportive today."
        ],
    7: [
        "You seem to have good energy today.",
        "Today's mood reads as energized and upbeat.",
        "You're on the higher end of your energy range.",
        "This check-in points to a strong, positive day.",
        "Energy feels solid and ready for action.",
        "You have good energy today!",
        "This is a strong, positive day.",
        "Energy feels vibrant and active.",
         "You’re feeling strong and capable today.",
        "Energy’s active — you’re in flow.",
        "You’re motivated and focused — great combination.",
        "This is a productive, upbeat day.",
        "Energy’s strong — things will move easily.",
        "You’re in control and ready to engage.",
        "Your mood feels optimistic and clear.",
        "Energy’s sharp — use it well.",
        "You’re alert and efficient — momentum’s with you.",
        "This is a get-things-done kind of day.",
        "You’re grounded yet driven.",
        "Energy supports deep work today.",
        "You’re operating at a healthy rhythm.",
        "You’re in the sweet spot — balanced intensity.",
        "This is a flow-state day — stay focused.",
        "Energy’s stable and active — good conditions ahead.",
        "You’re calm but productive — great balance.",
        "You’re fully present and performing well.",
        "Energy’s high enough to push forward strongly.",
        "You’re in strong, confident form today."
        "You’re in a good flow today.",
        "Energy is helping you stay focused and engaged."
    ],
    8: [
        "You're feeling very energized today!",
        "You’re energized and purposeful today.",
        "Energy’s high — great time for meaningful action.",
        "You feel motivated, focused, and creative.",
        "This is a high-momentum day — make it count.",
        "Energy’s buzzing — channel it productively.",
        "You’re glowing with clarity and drive.",
        "You’re highly engaged — stay intentional.",
        "Energy’s bold but grounded — perfect balance.",
        "You’re radiating confidence — let it guide you.",
        "This is an inspired day — flow freely.",
        "You’re energized without chaos — ideal state.",
        "Energy’s vibrant — push something forward.",
        "You’re leading your day with strength.",
        "This is your high-performing mode — enjoy it.",
        "Energy’s solid — no overthinking needed.",
        "You’re creatively alive — run with it.",
        "You’re on a roll — keep momentum steady.",
        "Energy’s empowering you to act clearly.",
        "You’re bright and focused — good synergy today.",
        "This is an energetic but balanced peak."
        "You're radiating positivity and drive right now.",
        "You're very energized today!",
        "This is a high-energy, action-driven day.",
        "You feel motivated and ready to move.",
        "You might feel excited and eager to act.",
        "You’re operating at an impressive level today.",
        "Your energy feels bright and productive.",
        "You’re running with purpose right now.",
        "You’re radiating positivity and drive today.",
        "This is a high-performance mood state.",
        "You’re powered up and moving forward fast.",
        ],
    9: [
        "You're highly energized today!",
        "Today's check-in points to peak focus and motivation.",
        "Energy is at a powerful high — you can get a lot done.",
        "You're running at near-peak capacity right now.",
        "This is a strong, high-momentum day.",
        "You're highly energized today!",
        "This is near peak energy — full momentum ahead.",
        "Energy feels electric and powerful.",
        "You might feel unstoppable right now.",
        "This is an action-packed day waiting to happen.",
        "You’re charged up and fully alive today.",
        "Energy feels sharp and clear.",
        "This is a great day to chase big goals.",
        "You’re on fire today — use it well.",
        "Energy is near its peak right now.",
        "You might feel a rush of motivation today.",
        "This is a bold, confident energy state.",
        "You’re at the top of your focus range.",
        "Energy feels fast and powerful.",
        "You might feel like taking on challenges today.",
        "This is a day to push boundaries.",
        "Energy is in full swing right now.",
        "You’re hitting your stride.",
        "This is a strong performance day.",
        "Energy feels supercharged and ready."
        ],
    10: [
        "You're at peak energy today!",
        "This is a max-energy day — full of vitality and drive.",
        "Today's check-in shows you're completely charged up.",
        "You're at your absolute best right now — great time for big wins.",
        "Energy is sky-high — this is a top-performance day.",
        "You're at absolute peak energy today!",
        "This is max level — you’re unstoppable.",
        f"Energy is at {energy}% capacity right now.",
        "You might feel like conquering the world today.",
        "This is your top performance state.",
        "Energy is firing on all cylinders.",
        "You’re fully charged and ready for big wins.",
        "This is a flow-state kind of day.",
        "You might feel completely unstoppable right now.",
        "Energy is at its highest — strike while it’s hot.",
        "You’re performing at your absolute best today.",
        "This is a superpowered check-in.",
        "Energy feels limitless right now.",
        "You might feel euphoric or invincible today.",
        "This is a prime state for peak results.",
        "You’re overflowing with drive and focus.",
        "Energy is maxed out — time to go big.",
        "You’re in rare form today — take advantage of it.",
        "This is a legendary energy day.",
    "You’re at full strength — perfect for major action."
    ]}
    
    overall_mood_message = random.choice(energyMessages[energy])
    
    return overall_mood_message